### PR TITLE
Logo colors

### PR DESCRIPTION
**Pull request by chris-hammond**
**What kind of change does this PR introduce?**

Changed static files for atom logos to match the colors on the presentation/poster. 

**Does this PR introduce a breaking change?**

The only problem with this is that our screenshots on the poster and presentation are out-of-date if we merge this.

Overall, I think it still makes sense to do...

### CODE REVIEW

**Comment by kjh61998** [comment]
The only thing I noticed is that on the favicon on the tab itself, the background of the logo no longer matches the background of the tab. I'm not sure how to fix that.

**Comment by chris-hammond** [comment]
The favicon problem was because I created the png from inkscape, and apparently it adds a white background when it does that... It has been fixed!

**Comment by liliedelamotte** [comment]
Hmm, doesn't seem to be fixed on my end.

**Comment by kjh61998** [comment]
> Hmm, doesn't seem to be fixed on my end.

Did you use the most recent build/deploy? It's fixed on my end

**Comment by chris-hammond** [comment]
Try control-shift-R. You're probably caching the old version.

The yellow does get kinda lost in the favicon, though...

**Comment by liliedelamotte** [comment]
Ah, it was caching the old version. Looks good now.

**Pull request merged**
