### PR TITLE
Create Static Template for Home Page

### PR DESCRIPTION
**Pull request by liliedelamotte**
Added a large slogan and two section titles for the home page. Featured projects and success stories will appear here when projects are created in the database.

### CODE REVIEW

**Comment by chris-hammond** [comment]
The build preview looks a little funky: https://deploy-preview-5--tech-connect.netlify.com/ Is it correct, or are some images broken?

**Comment by liliedelamotte** [comment]
No, it looks bare right now because the main content will be projects pulled from the database, which we don't have yet.

**Comment by chris-hammond** [comment]
I thought there was more static content on the homepage? Maybe some sort of call to action?

**Comment by chris-hammond** [comment]
Can you share a screenshot of the page with your local test database?

**Comment by liliedelamotte** [comment]
The only other piece of content in the mockup was a quote, which we decided to forego for the meantime because creating a template for  the `index.js` page to edit that single quote was proving to be slightly difficult, and getting bogged down with details such as that might prevent us from making progress as a whole.

We can definitely add a call to action though -- think maybe adding links to the future Create Project and View All Projects page inside the content of the home page would be a good way to do that?

As for pulling from a local database, currently I don't have one up and running so I'm not sure how I would be able to make that happen?

**Comment by chris-hammond** [comment]
I have a hard time merging this as it is. I think at a minimum this should have some placeholder divs for how the user content will be arranged.

Do we wait to merge this until we have gatsby and strapi talking?

**Pull request merged**
