### PR TITLE
Clean Up Repo

### PR DESCRIPTION
**Pull request by liliedelamotte**
This PR removes excess images and default template files that we're no longer using.

### CODE REVIEW

**Comment by kjh61998** [comment]
Hey, so all of the checks failed. I re-ran the checks and didn't see a change.

**Comment by liliedelamotte** [comment]
Whoops, weird! Thanks for letting me know, I'll look into it.

**Comment by chris-hammond** [comment]
From the build logs:

3:43:10 PM: Cannot query field "tags" on type "MarkdownRemarkFrontmatter".
3:43:10 PM: GraphQL request (11:15)
3:43:10 PM: 10:             frontmatter {
3:43:10 PM: 11:               tags
3:43:10 PM:                   ^
3:43:10 PM: 12:               templateKey
3:43:10 PM: error gatsby-node.js returned an error
3:43:10 PM: 
3:43:10 PM:   GraphQLError: Cannot query field "tags" on type "MarkdownRemarkFrontmatter".
3:43:10 PM:   
3:43:10 PM:   - new Promise
3:43:10 PM:   
3:43:10 PM:   - index.js:358 graphqlRunner

**Comment by liliedelamotte** [comment]
I'm closing this PR since it's a little broken and @kjh61998 is merging Tag changes in a different PR. The changes this PR introduced will be done correctly on a separate branch pulled from the updated master branch.

**Pull request closed without merging**
