### PR TITLE
Adding AUTH for gatsby-source-strapi. Updating packages.

### PR DESCRIPTION
**Pull request by chris-hammond**
Just updating packages and adding authentication for gatsby-source-strapi so we we can "secure" our API.

### CODE REVIEW

**Comment by chris-hammond** [comment]
Once you have strapi running locally, (See https://github.com/gfu-servant-engineering/tech-connect-backend/pull/11) change the strapi hostname in your .env.development file to localhost:1337 then run the following commands:
`yarn install`
`yarn develop`

**Comment by RanDumSocks** [comment]
In order for me to get this to work, I had to comment out the password identifier for the `gastby-source-strapi` plugin in `gatsby-config.js`

**Comment by chris-hammond** [comment]
@RanDumSocks Do you mean line 39? Is that because it was missing from your .env file?

**Comment by RanDumSocks** [comment]
@chris-hammond yea line 39, my .env file was set up fine. I couldn't tell ya why having the credentials failed and leaving them blank worked.

**Pull request merged**
